// Universal URDF (Unified Robot Description Format) Parser & Exporter
// Works seamlessly in both Node.js (test/server) and Browser environments.

const DEG2RAD = Math.PI / 180;
const RAD2DEG = 180 / Math.PI;

function round(val, decimals = 4) {
  return Number(Math.round(val + 'e' + decimals) + 'e-' + decimals);
}

/**
 * Exports a serial robot DH joint configuration to a standard ROS URDF XML string.
 * @param {Array} joints - Normalized DH joint array
 * @param {string} robotName - Name of the robot
 * @returns {string} URDF XML string
 */
export function exportToURDF(joints, robotName = 'DH_Robot') {
  if (!Array.isArray(joints) || joints.length === 0) {
    throw new Error('Nenhuma junta fornecida para exportação URDF.');
  }

  const cleanName = robotName.replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase() || 'dh_robot';
  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<!-- Generated by DH Robot Kinematics Platform -->\n`;
  xml += `<robot name="${cleanName}">\n\n`;

  // Material definitions for rich visualization in RViz / WebGL
  xml += `  <material name="pedestal_mat">\n    <color rgba="0.2 0.25 0.32 1.0"/>\n  </material>\n`;
  xml += `  <material name="link_accent">\n    <color rgba="0.23 0.51 0.96 1.0"/>\n  </material>\n`;
  xml += `  <material name="motor_mat">\n    <color rgba="0.93 0.28 0.6 1.0"/>\n  </material>\n`;
  xml += `  <material name="tool_gold">\n    <color rgba="0.96 0.77 0.19 1.0"/>\n  </material>\n\n`;

  // Base link (pedestal)
  xml += `  <link name="base_link">\n`;
  xml += `    <visual>\n`;
  xml += `      <origin xyz="0 0 0.1" rpy="0 0 0"/>\n`;
  xml += `      <geometry>\n        <cylinder radius="0.35" length="0.2"/>\n      </geometry>\n`;
  xml += `      <material name="pedestal_mat"/>\n`;
  xml += `    </visual>\n`;
  xml += `    <collision>\n`;
  xml += `      <origin xyz="0 0 0.1" rpy="0 0 0"/>\n`;
  xml += `      <geometry>\n        <cylinder radius="0.35" length="0.2"/>\n      </geometry>\n`;
  xml += `    </collision>\n`;
  xml += `  </link>\n\n`;

  let prevLink = 'base_link';

  joints.forEach((joint, idx) => {
    const jointNum = idx + 1;
    const jointName = `joint_${jointNum}`;
    const linkName = `link_${jointNum}`;
    const isRevolute = joint.type === 'R';
    const urdfType = isRevolute ? 'revolute' : 'prismatic';

    // In serial DH, translation along Z is d, translation along X is a, twist along X is alpha
    // Origin of this joint relative to the previous link
    const x = round(joint.a ?? 0);
    const z = round(joint.d ?? 0);
    const alphaRad = round((joint.alpha ?? 0) * DEG2RAD);

    // Axis is always Z (0 0 1) in standard DH convention
    const axisX = 0;
    const axisY = 0;
    const axisZ = 1;

    // Limits in standard units: rad for revolute, meters/units for prismatic
    const lower = isRevolute ? round((joint.min ?? -180) * DEG2RAD) : round(joint.min ?? 0);
    const upper = isRevolute ? round((joint.max ?? 180) * DEG2RAD) : round(joint.max ?? 10);
    const velocity = isRevolute
      ? round((joint.speed && joint.speed > 0 ? joint.speed : 180) * DEG2RAD)
      : round(joint.speed && joint.speed > 0 ? joint.speed : 2.0);

    xml += `  <!-- Joint ${jointNum} (${joint.type}) -->\n`;
    xml += `  <joint name="${jointName}" type="${urdfType}">\n`;
    xml += `    <parent link="${prevLink}"/>\n`;
    xml += `    <child link="${linkName}"/>\n`;
    xml += `    <origin xyz="${x} 0 ${z}" rpy="${alphaRad} 0 0"/>\n`;
    xml += `    <axis xyz="${axisX} ${axisY} ${axisZ}"/>\n`;
    xml += `    <limit lower="${lower}" upper="${upper}" effort="150.0" velocity="${velocity}"/>\n`;
    xml += `  </joint>\n\n`;

    // Link representation
    const linkLength = Math.max(0.2, Math.sqrt(x * x + z * z));
    xml += `  <link name="${linkName}">\n`;
    xml += `    <visual>\n`;
    xml += `      <origin xyz="${round(x / 2)} 0 ${round(z / 2)}" rpy="0 0 0"/>\n`;
    xml += `      <geometry>\n        <cylinder radius="0.08" length="${round(linkLength)}"/>\n      </geometry>\n`;
    xml += `      <material name="link_accent"/>\n`;
    xml += `    </visual>\n`;
    xml += `    <collision>\n`;
    xml += `      <origin xyz="${round(x / 2)} 0 ${round(z / 2)}" rpy="0 0 0"/>\n`;
    xml += `      <geometry>\n        <cylinder radius="0.08" length="${round(linkLength)}"/>\n      </geometry>\n`;
    xml += `    </collision>\n`;
    xml += `  </link>\n\n`;

    prevLink = linkName;
  });

  // End-effector tool attachment
  xml += `  <!-- Tool0 / End-Effector -->\n`;
  xml += `  <link name="tool0">\n`;
  xml += `    <visual>\n`;
  xml += `      <origin xyz="0 0 0" rpy="0 0 0"/>\n`;
  xml += `      <geometry>\n        <sphere radius="0.12"/>\n      </geometry>\n`;
  xml += `      <material name="tool_gold"/>\n`;
  xml += `    </visual>\n`;
  xml += `  </link>\n\n`;
  xml += `  <joint name="joint_ee_fixed" type="fixed">\n`;
  xml += `    <parent link="${prevLink}"/>\n`;
  xml += `    <child link="tool0"/>\n`;
  xml += `    <origin xyz="0 0 0" rpy="0 0 0"/>\n`;
  xml += `  </joint>\n\n`;

  xml += `</robot>\n`;
  return xml;
}

/**
 * Universal XML tag value extractor using regex for platform portability
 */
function extractAttr(tagString, attrName) {
  const match = new RegExp(`${attrName}\\s*=\\s*["']([^"']*)["']`, 'i').exec(tagString);
  return match ? match[1] : null;
}

/**
 * Parses a standard URDF XML string into normalized DH joints.
 * @param {string} urdfString - URDF XML content
 * @returns {Array} Array of DH joints
 */
export function parseURDF(urdfString) {
  if (typeof urdfString !== 'string' || !urdfString.trim()) {
    throw new Error('Arquivo URDF vazio ou inválido.');
  }

  if (!/<robot[\s\S]*?>[\s\S]*<\/robot>/i.test(urdfString)) {
    throw new Error('Formato URDF inválido: tag <robot> não encontrada.');
  }

  // Extract all <joint> blocks
  const jointRegex = /<joint\b([\s\S]*?)>([\s\S]*?)<\/joint>/gi;
  const parsedJoints = [];
  let match;

  while ((match = jointRegex.exec(urdfString)) !== null) {
    const jointHeader = match[1];
    const jointBody = match[2];

    const name = extractAttr(jointHeader, 'name') || `joint_${parsedJoints.length + 1}`;
    const typeStr = (extractAttr(jointHeader, 'type') || 'revolute').toLowerCase();

    // Skip fixed joints like base-to-world or end-effector
    if (typeStr === 'fixed' || name.toLowerCase().includes('fixed') || name.toLowerCase().includes('tool')) {
      continue;
    }

    const type = typeStr === 'prismatic' ? 'P' : 'R';

    // Parse <origin xyz="..." rpy="..."/>
    const originMatch = /<origin\b([\s\S]*?)\/?>/i.exec(jointBody);
    let xyz = [0, 0, 0];
    let rpy = [0, 0, 0];
    if (originMatch) {
      const xyzStr = extractAttr(originMatch[1], 'xyz');
      const rpyStr = extractAttr(originMatch[1], 'rpy');
      if (xyzStr) xyz = xyzStr.trim().split(/\s+/).map(Number);
      if (rpyStr) rpy = rpyStr.trim().split(/\s+/).map(Number);
    }

    // In standard DH:
    // a is length along X, d is offset along Z, alpha is rotation along X in degrees
    const a = round(xyz[0] || 0, 2);
    const d = round(xyz[2] || 0, 2);
    const alpha = round((rpy[0] || 0) * RAD2DEG, 2);

    // Parse <limit lower="..." upper="..." velocity="..."/>
    const limitMatch = /<limit\b([\s\S]*?)\/?>/i.exec(jointBody);
    let lower = type === 'R' ? -180 : 0;
    let upper = type === 'R' ? 180 : 10;
    let speed = 0;

    if (limitMatch) {
      const lowerAttr = extractAttr(limitMatch[1], 'lower');
      const upperAttr = extractAttr(limitMatch[1], 'upper');
      const velAttr = extractAttr(limitMatch[1], 'velocity');

      if (lowerAttr !== null && !isNaN(Number(lowerAttr))) {
        lower = type === 'R' ? round(Number(lowerAttr) * RAD2DEG, 1) : round(Number(lowerAttr), 2);
      }
      if (upperAttr !== null && !isNaN(Number(upperAttr))) {
        upper = type === 'R' ? round(Number(upperAttr) * RAD2DEG, 1) : round(Number(upperAttr), 2);
      }
      if (velAttr !== null && !isNaN(Number(velAttr))) {
        speed = type === 'R' ? round(Number(velAttr) * RAD2DEG, 1) : round(Number(velAttr), 2);
      }
    }

    const defaultVal = type === 'R' ? 0 : Math.max(0, d);

    parsedJoints.push({
      id: parsedJoints.length + 1,
      type,
      a,
      alpha,
      theta: type === 'R' ? defaultVal : 0,
      d: type === 'P' ? defaultVal : d,
      val: defaultVal,
      min: lower,
      max: upper,
      speed,
    });
  }

  if (parsedJoints.length === 0) {
    throw new Error('Nenhuma junta móvel (revolute/prismatic) encontrada no arquivo URDF.');
  }

  return parsedJoints;
}
